services:

  mysql:
    image: mysql:8.0
    container_name: seeat-mysql
    volumes:
      - ./mysql/my.cnf:/etc/mysql/conf.d/mytv.cnf
      - ./mysql/data:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

